version: '3.7'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: schedule-server
    container_name: schedule-node-server
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: schedule-client
    container_name: schedule-react-client
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
